### ISSUE TITLE
Waybar config looks diferent

### ISSUE THREAD

**Issue by LudovicoPiero** [angelofallars/dotfiles#1]
So i just copy your waybar config to my .config file and this is what it's looks like
![image](https://user-images.githubusercontent.com/44255157/163636007-3dc7149c-212c-4b06-ad39-bbd88076aac1.png)
And this is the output when i ran it from terminal
![image](https://user-images.githubusercontent.com/44255157/163636168-c21bf7ea-d461-4a71-b9f8-577ee87f8ae2.png)

**Comment by angelofallars** [comment]
I've updated my waybar config. I haven't updated the images on my repo unluckily.

**Comment by LudovicoPiero** [comment]
So, this is the new one? if so, how can i get the old one?
